spring.application.name=clientes-service

# CONFIGURACIÓN DE credenciales de MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/clientes_test
spring.datasource.username=root
#Clave.De.Admin-0
spring.datasource.password=

# CONFIGURACIÓN DE SPRING CON MYSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Para quitar el aviso anterior del "Open In View"
spring.jpa.open-in-view=false